apiVersion: v1
kind: Service
metadata:
  name: {{ include "mario-chart.fullname" . }}
  labels:
    {{- include "mario-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "mario-chart.name" . }}
